/**
 * One run, as Markdown — the body of a CI pull request and the job summary (D-032).
 *
 * Written for the reviewer, who is the last line of defence the threat model
 * relies on (T9): what was fixed and by which commit, what it cost, and, folded
 * away, everything the loop learned about what it could not fix. It says plainly
 * that passing the checks is not the same as being right.
 */
import type { IssueOutcome, RunReport } from '@self-heal/core/runner/runner';

export interface RunMarkdownInput {
  readonly report: RunReport;
  /** Signature → the escalation hand-off: where it was written, and its text. */
  readonly escalations: ReadonlyMap<string, { readonly path: string; readonly markdown: string }>;
  readonly calls: readonly { readonly costUsd: number | null }[];
  /** The fix commits this run made, oldest first. */
  readonly commits: readonly { readonly sha: string; readonly subject: string }[];
}

/** GitHub rejects a PR body over 65,536 characters; leave room for the footer. */
export const RUN_MARKDOWN_LIMIT = 60_000;

const MARK: Record<IssueOutcome['state'], string> = {
  HEALED: '✅',
  RESOLVED: '✅',
  FLAKY: '〰️',
  PROPOSED: '·',
  REVERTED: '❌',
  ESCALATED: '⚠️',
};

export function renderRunMarkdown(input: RunMarkdownInput): string {
  const { report } = input;
  const fixed = report.outcomes.filter((o) => o.state === 'HEALED' || o.state === 'RESOLVED').length;

  const head: string[] = [
    `## self-heal: ${report.issues === 0 ? 'no issues detected' : `${fixed} of ${report.issues} issue(s) fixed`}`,
    '',
  ];
  if (report.halted) head.push(`> **Halted:** ${report.haltReason ?? 'unknown reason'}`, '');
  if (input.commits.length > 0) {
    head.push(
      '> Each fix below passed the check that found the problem, and no other check newly failed.',
      '> That is what the checks can prove. **Review the diff before merging** — they cannot prove intent.',
      '',
    );
  }

  if (report.outcomes.length > 0) {
    head.push('| | Issue | Outcome | Why |', '|---|---|---|---|');
    for (const outcome of report.outcomes) {
      head.push(
        `| ${MARK[outcome.state]} | \`${outcome.issue.kind}\` \`${outcome.issue.signature.slice(0, 8)}\` | ${outcome.state} | ${cell(outcome.reason)} |`,
      );
    }
    head.push('');
  }

  if (input.commits.length > 0) {
    head.push('### Commits', '', ...input.commits.map((c) => `- \`${c.sha}\` ${c.subject}`), '');
  }

  head.push('### Spend', '', spendLine(input.calls), '');

  // Escalations last and folded: the longest part, and the part a reviewer of the
  // fixes needs least. Dropped whole, never cut mid-section, when over the limit.
  const footer = '\n---\n_Generated by [self-heal](https://github.com/Ali7040/heal). Commits are authored `self-heal`; revert any one on its own._\n';
  let body = head.join('\n');
  const omitted: string[] = [];
  for (const outcome of report.outcomes) {
    const escalation = input.escalations.get(outcome.issue.signature);
    if (escalation === undefined) continue;
    const section = [
      `### Escalated: \`${outcome.issue.kind}\` \`${outcome.issue.signature.slice(0, 8)}\``,
      '',
      '<details><summary>What was tried, and why it failed</summary>',
      '',
      escalation.markdown.trimEnd(),
      '',
      '</details>',
      '',
    ].join('\n');
    if (body.length + section.length + footer.length > RUN_MARKDOWN_LIMIT) {
      omitted.push(escalation.path);
      continue;
    }
    body += `\n${section}`;
  }
  if (omitted.length > 0) {
    body += `\n_${omitted.length} escalation report(s) left out for length — in the job's evidence: ${omitted.map((p) => `\`${p}\``).join(', ')}_\n`;
  }

  return `${body.trimEnd()}\n${footer}`;
}

function spendLine(calls: RunMarkdownInput['calls']): string {
  if (calls.length === 0) return 'No model calls.';
  const known = calls.reduce((total, call) => total + (call.costUsd ?? 0), 0);
  const unknown = calls.filter((call) => call.costUsd === null).length;
  const amount = unknown === 0 ? `$${known.toFixed(4)}` : `at least $${known.toFixed(4)} (${unknown} call(s) did not report a cost)`;
  return `${amount} over ${calls.length} model call(s).`;
}

/** A table cell: one line, and no pipe that would split it. */
function cell(text: string): string {
  return text.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|');
}
